### ISSUE TITLE
Can YADCC use a universal build framework like CMake, SCons or others?

### ISSUE THREAD

**Issue by CrazyWood2020** [Tencent/yadcc#12]
Most community contributors rarely know about blade, when we want to add address sanitizer option for this project, we get confused.

**Comment by 0x804d8000** [comment]
Adding `-fsanitize=address` to [`cxxflags`](https://github.com/Tencent/flare/blob/d41ae2e5fdec1db1ed54f5cf6c829097a96a4541/BLADE_ROOT#L39) and [`linkflags`](https://github.com/Tencent/flare/blob/d41ae2e5fdec1db1ed54f5cf6c829097a96a4541/BLADE_ROOT#L105) in `BLADE_ROOT` should do the trick.

Unlike [flare](https://github.com/Tencent/flare), which is mostly imported to other code repository by source, I'd expect most of the users of yadcc care more about using it rather than hacking on the code, so I'm not sure it's worth the effort to support other building systems.

**Comment by CrazyWood2020** [comment]
OK, get it. Tks~
